#!/usr/bin/env bash
# Sets up (or updates) the nightly build on a host, as root:
#
#   sudo ./systemd/install.sh
#
# Runs the build as the system user qlever-plazi from /opt/qlever-plazi, with
# the host settings in /etc/qlever-plazi.env. On a new host the first call
# creates that file from qlever-plazi.env.example and stops, so it can be
# edited; the second call finishes the setup and runs the first build.
# Safe to run again.
set -euo pipefail

SERVICE_USER=qlever-plazi
CODE=/opt/qlever-plazi
CONFIG=/etc/qlever-plazi.env
REPO_URL=https://github.com/plazi/qlever-plazi.git
SRC=$(cd "$(dirname "$0")/.." && pwd)

[ "$(id -u)" = 0 ] || { echo "run as root: sudo $0" >&2; exit 1; }
step() { echo; echo "== $*"; }

step "host settings in $CONFIG"
if [ ! -f "$CONFIG" ]; then
  install -m 644 "$SRC/qlever-plazi.env.example" "$CONFIG"
  echo "created $CONFIG from the example: edit it (QP_ROOT, QP_NETWORK, ...), then run $0 again"
  exit 0
fi
# setting KEY: its value in $CONFIG, without optional surrounding quotes
setting() {
  sed -n "s/^$1=//p" "$CONFIG" | tail -n 1 | sed -E "s/^\"(.*)\"\$/\1/; s/^'(.*)'\$/\1/"
}
QP_ROOT=$(setting QP_ROOT)
QP_NETWORK=$(setting QP_NETWORK)
QP_HOST=$(setting QP_HOST)
QP_HOST=${QP_HOST:-qlever.ld.plazi.org}
case $QP_ROOT in
  /?*) ;;
  *) echo "QP_ROOT in $CONFIG must be an absolute path, not '$QP_ROOT'" >&2; exit 1 ;;
esac
[ "$QP_ROOT" != / ] || { echo "QP_ROOT must not be /" >&2; exit 1; }
docker network inspect "$QP_NETWORK" > /dev/null 2>&1 ||
  { echo "QP_NETWORK in $CONFIG: no Docker network '$QP_NETWORK'" >&2; exit 1; }
echo "QP_ROOT=$QP_ROOT QP_NETWORK=$QP_NETWORK QP_HOST=$QP_HOST"

step "no other deployment serving $QP_HOST"
# Another server routed by Traefik to the same host would keep answering next
# to ours (the switch only stops containers of this setup), and another
# scheduled build would compete for the same data. Retire them first.
# (all containers of this setup are named qlever-plazi-...)
others=$(docker ps -q | xargs -r docker inspect -f '{{.Name}} {{range $k, $v := .Config.Labels}}{{$v}} {{end}}' |
  grep -F "Host(\`$QP_HOST\`)" | grep -v '^/qlever-plazi-' | cut -d' ' -f1 || true)
schedules=$(grep -l 'qlever-plazi.sh' /var/spool/cron/crontabs/* /etc/crontab /etc/cron.d/* 2> /dev/null || true)
if [ -n "$others$schedules" ]; then
  [ -z "$others" ] || echo "running containers serving $QP_HOST outside this setup:" $others >&2
  [ -z "$schedules" ] || echo "crontabs that run qlever-plazi.sh:" $schedules >&2
  echo "stop or remove them (and take them out of their compose file), then run $0 again" >&2
  exit 1
fi
echo "none"

step "service user $SERVICE_USER"
if ! id "$SERVICE_USER" > /dev/null 2>&1; then
  useradd --system --user-group --create-home --home-dir "/var/lib/$SERVICE_USER-home" \
    --shell /usr/sbin/nologin "$SERVICE_USER"
fi
# Also when the user existed already: the unit runs with this group, and the
# build needs Docker
getent group "$SERVICE_USER" > /dev/null || groupadd --system "$SERVICE_USER"
usermod -g "$SERVICE_USER" -aG docker "$SERVICE_USER"
id "$SERVICE_USER"

step "data in $QP_ROOT"
mkdir -p "$QP_ROOT"
chown "$SERVICE_USER:" "$QP_ROOT"

step "code in $CODE"
if [ ! -d "$CODE/.git" ]; then
  git clone --quiet "$REPO_URL" "$CODE"
fi
chown -R "$SERVICE_USER:" "$CODE"
sudo -u "$SERVICE_USER" git -C "$CODE" pull --ff-only --quiet
sudo -u "$SERVICE_USER" git -C "$CODE" log --oneline -1

step "systemd units"
install -m 644 "$CODE/systemd/qlever-plazi.service" "$CODE/systemd/qlever-plazi.timer" /etc/systemd/system/
mkdir -p /etc/systemd/system/qlever-plazi.service.d
printf '[Unit]\n# Generated by install.sh from %s\nRequiresMountsFor=%s\n' "$CONFIG" "$QP_ROOT" \
  > /etc/systemd/system/qlever-plazi.service.d/data.conf
systemctl daemon-reload
systemctl enable --now qlever-plazi.timer

if [ -f "$QP_ROOT/current/stamp.json" ]; then
  step "done (an index is live already; the timer builds the next one)"
else
  step "first run (about 30 minutes; progress: journalctl -fu qlever-plazi)"
  systemctl start qlever-plazi.service ||
    { echo "first run FAILED, see: journalctl -u qlever-plazi" >&2; exit 1; }
fi
systemctl list-timers qlever-plazi.timer --no-pager
